//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/ANtek/Scripts/WaiterController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @WaiterController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @WaiterController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""WaiterController"",
    ""maps"": [
        {
            ""name"": ""Waiter"",
            ""id"": ""be07f211-55c9-4ef9-813a-e5baf82f7d5e"",
            ""actions"": [
                {
                    ""name"": ""Movement_Waiter"",
                    ""type"": ""Value"",
                    ""id"": ""7f449d04-2f00-4226-902d-1541470315dd"",
                    ""expectedControlType"": """",
                    ""processors"": ""AxisDeadzone,AxisDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement_FuckingRat"",
                    ""type"": ""Value"",
                    ""id"": ""f41ea76e-51ea-4be7-a416-bef0c6a5d7dd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""859749e1-5061-4a1e-8686-1da597a6b18f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_Waiter"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f9cc6b65-cb04-42b1-9cae-fc222a299774"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_Waiter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""841d777c-428b-41d8-8497-09211761358d"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_Waiter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f7076803-f32a-4798-9a1c-245893307a25"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_Waiter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""993d2f46-0c5d-4b18-a1b7-2288ad25f571"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_Waiter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2fa2e008-3c51-413a-87b4-16021b0b8798"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_FuckingRat"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e40579cf-79e5-4573-bd98-01bc237d494b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_FuckingRat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""07e00918-64c7-4f1f-a875-4cea805f1900"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_FuckingRat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c94ff843-4890-46eb-ab10-df772523ee61"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_FuckingRat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""642153ab-4d3d-4998-bc6c-b22615a77e84"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement_FuckingRat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Waiter
        m_Waiter = asset.FindActionMap("Waiter", throwIfNotFound: true);
        m_Waiter_Movement_Waiter = m_Waiter.FindAction("Movement_Waiter", throwIfNotFound: true);
        m_Waiter_Movement_FuckingRat = m_Waiter.FindAction("Movement_FuckingRat", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Waiter
    private readonly InputActionMap m_Waiter;
    private List<IWaiterActions> m_WaiterActionsCallbackInterfaces = new List<IWaiterActions>();
    private readonly InputAction m_Waiter_Movement_Waiter;
    private readonly InputAction m_Waiter_Movement_FuckingRat;
    public struct WaiterActions
    {
        private @WaiterController m_Wrapper;
        public WaiterActions(@WaiterController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement_Waiter => m_Wrapper.m_Waiter_Movement_Waiter;
        public InputAction @Movement_FuckingRat => m_Wrapper.m_Waiter_Movement_FuckingRat;
        public InputActionMap Get() { return m_Wrapper.m_Waiter; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WaiterActions set) { return set.Get(); }
        public void AddCallbacks(IWaiterActions instance)
        {
            if (instance == null || m_Wrapper.m_WaiterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WaiterActionsCallbackInterfaces.Add(instance);
            @Movement_Waiter.started += instance.OnMovement_Waiter;
            @Movement_Waiter.performed += instance.OnMovement_Waiter;
            @Movement_Waiter.canceled += instance.OnMovement_Waiter;
            @Movement_FuckingRat.started += instance.OnMovement_FuckingRat;
            @Movement_FuckingRat.performed += instance.OnMovement_FuckingRat;
            @Movement_FuckingRat.canceled += instance.OnMovement_FuckingRat;
        }

        private void UnregisterCallbacks(IWaiterActions instance)
        {
            @Movement_Waiter.started -= instance.OnMovement_Waiter;
            @Movement_Waiter.performed -= instance.OnMovement_Waiter;
            @Movement_Waiter.canceled -= instance.OnMovement_Waiter;
            @Movement_FuckingRat.started -= instance.OnMovement_FuckingRat;
            @Movement_FuckingRat.performed -= instance.OnMovement_FuckingRat;
            @Movement_FuckingRat.canceled -= instance.OnMovement_FuckingRat;
        }

        public void RemoveCallbacks(IWaiterActions instance)
        {
            if (m_Wrapper.m_WaiterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWaiterActions instance)
        {
            foreach (var item in m_Wrapper.m_WaiterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WaiterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WaiterActions @Waiter => new WaiterActions(this);
    public interface IWaiterActions
    {
        void OnMovement_Waiter(InputAction.CallbackContext context);
        void OnMovement_FuckingRat(InputAction.CallbackContext context);
    }
}
